[package]
name = "lazyrip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-to-tui = "3.1.0"
crossterm = "0.27.0"
ratatui = "0.24.0"
tui-textarea = "0.3.0"
